# .github/workflows/mongodb-replication.yml
name: MongoDB Replication

# Este workflow se activa cuando recibe un dispatch desde la API
on:
  repository_dispatch:
    types: [mongodb-replication]

jobs:
  replicate-to-mongodb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node
        run: npm install -g ts-node typescript

      - name: Execute MongoDB replication
        run: ts-node ./src/jobs/replications/ReplicateToRDP03Instances.ts
        env:
          # Parámetros del evento
          MONGO_OPERATION: ${{ toJSON(github.event.client_payload.operation) }}
          INSTANCIAS_A_ACTUALIZAR: ${{ toJSON(github.event.client_payload.instanciasAActualizar) }}
          TIMESTAMP: ${{ github.event.client_payload.timestamp }}

          # Variables para las conexiones de base de datos MongoDB
          RDP03_INS1_DATABASE_URL: ${{ secrets.RDP03_INS1_DATABASE_URL }}
          RDP03_INS2_DATABASE_URL: ${{ secrets.RDP03_INS2_DATABASE_URL }}
          RDP03_INS3_DATABASE_URL: ${{ secrets.RDP03_INS3_DATABASE_URL }}
          RDP03_INS4_DATABASE_URL: ${{ secrets.RDP03_INS4_DATABASE_URL }}
          RDP03_INS5_DATABASE_URL: ${{ secrets.RDP03_INS5_DATABASE_URL }}
          ENTORNO: ${{ secrets.ENTORNO }}

          # Configuraciones MongoDB opcionales
          # MONGO_MAX_POOL_SIZE: ${{ secrets.MONGO_MAX_POOL_SIZE }}
          # MONGO_MIN_POOL_SIZE: ${{ secrets.MONGO_MIN_POOL_SIZE }}
          # MONGO_CONNECTION_TIMEOUT: ${{ secrets.MONGO_CONNECTION_TIMEOUT }}
          # MONGO_SERVER_SELECTION_TIMEOUT: ${{ secrets.MONGO_SERVER_SELECTION_TIMEOUT }}

      - name: Notify completion
        if: always()
        run: |
          RESULT="${{ job.status }}"
          echo "Replicación MongoDB completada con estado: $RESULT"

          if [ "$RESULT" = "success" ]; then
            echo "✅ Todas las operaciones MongoDB se completaron exitosamente"
          else
            echo "❌ Ocurrieron errores durante la replicación MongoDB"
          fi